In [1]:
import pandas as pd

In [84]:
X_train = pd.read_csv("data/X_train.csv", encoding='cp949')
y_train = pd.read_csv("data/y_train.csv", encoding='cp949')
X_test = pd.read_csv("data/X_test.csv", encoding='cp949')

In [85]:
X_train["gender"] = y_train['gender']

In [86]:
X_train.head(5)

,cust_id,총구매액,최대구매액,환불금액,주구매상품,주구매지점,내점일수,내점당구매건수,주말방문비율,구매주기,gender
0,0,68282840,11264000,6860000.0,기타,강남점,19,3.894737,0.527027,17,0
1,1,2136000,2136000,300000.0,스포츠,잠실점,2,1.500000,0.000000,1,0
2,2,3197000,1639000,NaN,남성 캐주얼,관악점,2,2.000000,0.000000,1,1
3,3,16077620,4935000,NaN,기타,광주점,18,2.444444,0.318182,16,1
4,4,29050000,24000000,NaN,보석,본 점,2,1.500000,0.000000,85,0

In [87]:
X_train['환불금액'].fillna(0, inplace=True)

# EDA

In [38]:
X_train.groupby(['주구매상품','gender']).count().unstack()

       cust_id          총구매액         최대구매액          환불금액         주구매지점         \
gender       0      1      0      1      0      1      0      1      0      1
주구매상품
가공식품     317.0  229.0  317.0  229.0  317.0  229.0  317.0  229.0  317.0  229.0
가구         5.0    5.0    5.0    5.0    5.0    5.0    5.0    5.0    5.0    5.0
건강식품      22.0   25.0   22.0   25.0   22.0   25.0   22.0   25.0   22.0   25.0
골프        38.0   44.0   38.0   44.0   38.0   44.0   38.0   44.0   38.0   44.0
구두        26.0   28.0   26.0   28.0   26.0   28.0   26.0   28.0   26.0   28.0
기타       375.0  220.0  375.0  220.0  375.0  220.0  375.0  220.0  375.0  220.0
남성 캐주얼    13.0   42.0   13.0   42.0   13.0   42.0   13.0   42.0   13.0   42.0
남성 트랜디     1.0    1.0    1.0    1.0    1.0    1.0    1.0    1.0    1.0    1.0
남성정장       4.0   18.0    4.0   18.0    4.0   18.0    4.0   18.0    4.0   18.0
농산물      247.0   92.0  247.0   92.0  247.0   92.0  247.0   92.0  247.0   92.0
대형가전       4.0    4.0    4.0    4.0    4.0    4.0    4.0    4.0    4.0    4.0
디자이너     168.0   25.0  168.0   25.0  168.0   25.0  168.0   25.0  168.0   25.0
란제리/내의     6.0    2.0    6.0    2.0    6.0    2.0    6.0    2.0    6.0    2.0
명품        61.0   39.0   61.0   39.0   61.0   39.0   61.0   39.0   61.0   39.0
모피/피혁     39.0   18.0   39.0   18.0   39.0   18.0   39.0   18.0   39.0   18.0
보석         2.0    1.0    2.0    1.0    2.0    1.0    2.0    1.0    2.0    1.0
생활잡화       8.0    7.0    8.0    7.0    8.0    7.0    8.0    7.0    8.0    7.0
섬유잡화      48.0   50.0   48.0   50.0   48.0   50.0   48.0   50.0   48.0   50.0
셔츠        11.0   19.0   11.0   19.0   11.0   19.0   11.0   19.0   11.0   19.0
소형가전       1.0    1.0    1.0    1.0    1.0    1.0    1.0    1.0    1.0    1.0
수산품       92.0   61.0   92.0   61.0   92.0   61.0   92.0   61.0   92.0   61.0
스포츠       33.0   36.0   33.0   36.0   33.0   36.0   33.0   36.0   33.0   36.0
시티웨어     169.0   44.0  169.0   44.0  169.0   44.0  169.0   44.0  169.0   44.0
식기         2.0    5.0    2.0    5.0    2.0    5.0    2.0    5.0    2.0    5.0
아동        26.0   14.0   26.0   14.0   26.0   14.0   26.0   14.0   26.0   14.0
악기         NaN    2.0    NaN    2.0    NaN    2.0    NaN    2.0    NaN    2.0
액세서리       4.0    1.0    4.0    1.0    4.0    1.0    4.0    1.0    4.0    1.0
육류        31.0   26.0   31.0   26.0   31.0   26.0   31.0   26.0   31.0   26.0
일용잡화      43.0   21.0   43.0   21.0   43.0   21.0   43.0   21.0   43.0   21.0
젓갈/반찬     14.0   15.0   14.0   15.0   14.0   15.0   14.0   15.0   14.0   15.0
주류         3.0   11.0    3.0   11.0    3.0   11.0    3.0   11.0    3.0   11.0
주방가전       8.0   18.0    8.0   18.0    8.0   18.0    8.0   18.0    8.0   18.0
주방용품      18.0   14.0   18.0   14.0   18.0   14.0   18.0   14.0   18.0   14.0
차/커피      26.0   18.0   26.0   18.0   26.0   18.0   26.0   18.0   26.0   18.0
축산가공      19.0   16.0   19.0   16.0   19.0   16.0   19.0   16.0   19.0   16.0
침구/수예      4.0    NaN    4.0    NaN    4.0    NaN    4.0    NaN    4.0    NaN
캐주얼       60.0   41.0   60.0   41.0   60.0   41.0   60.0   41.0   60.0   41.0
커리어        6.0    3.0    6.0    3.0    6.0    3.0    6.0    3.0    6.0    3.0
통신/컴퓨터     1.0    2.0    1.0    2.0    1.0    2.0    1.0    2.0    1.0    2.0
트래디셔널     12.0   11.0   12.0   11.0   12.0   11.0   12.0   11.0   12.0   11.0
피혁잡화      21.0   19.0   21.0   19.0   21.0   19.0   21.0   19.0   21.0   19.0
화장품      196.0   68.0  196.0   68.0  196.0   68.0  196.0   68.0  196.0   68.0

         내점일수        내점당구매건수        주말방문비율          구매주기
gender      0      1       0      1      0      1      0      1
주구매상품
가공식품    317.0  229.0   317.0  229.0  317.0  229.0  317.0  229.0
가구        5.0    5.0     5.0    5.0    5.0    5.0    5.0    5.0
건강식품     22.0   25.0    22.0   25.0   22.0   25.0   22.0   25.0
골프       38.0   44.0    38.0   44.0   38.0   44.0   38.0   44.0
구두       26.0   28.0    26.0   28.0   26.0   28.0   26.0   28.0
기타      375.0  220.0   375.0  220.0  375.0  220.0  375.0  220.0
남성 캐주얼   13.0   42.0    13.0   42.0   13.0   42.0   13.0   42.0
남성 트랜디    1.0    1.0     1.0    1.0    1.0    1.0    1.0    1.0
남성정장      4.0   18.0     4.0   18.0    4.0   18.0    4.0   18.0
농산물     247.0   92.0   247.0   92.0  247.0   92.0  247.0   92.0
대형가전      4.0    4.0     4.0    4.0    4.0    4.0    4.0    4.0
디자이너    168.0   25.0   168.0   25.0  168.0   25.0  168.0   25.0
란제리/내의    6.0    2.0     6.0    2.0    6.0    2.0    6.0    2.0
명품       61.0   39.0    61.0   39.0   61.0   39.0   61.0   39.0
모피/피혁    39.0   18.0    39.0   18.0   39.0   18.0   39.0   18.0
보석        2.0    1.0     2.0    1.0    2.0    1.0    2.0    1.0
생활잡화      8.0    7.0     8.0    7.0    8.0    7.0    8.0    7.0
섬유잡화     48.0   50.0    48.0   50.0   48.0   50.0   48.0   50.0
셔츠       11.0   19.0    11.0   19.0   11.0   19.0   11.0   19.0
소형가전      1.0    1.0     1.0    1.0    1.0    1.0    1.0    1.0
수산품      92.0   61.0    92.0   61.0   92.0   61.0   92.0   61.0
스포츠      33.0   36.0    33.0   36.0   33.0   36.0   33.0   36.0
시티웨어    169.0   44.0   169.0   44.0  169.0   44.0  169.0   44.0
식기        2.0    5.0     2.0    5.0    2.0    5.0    2.0    5.0
아동       26.0   14.0    26.0   14.0   26.0   14.0   26.0   14.0
악기        NaN    2.0     NaN    2.0    NaN    2.0    NaN    2.0
액세서리      4.0    1.0     4.0    1.0    4.0    1.0    4.0    1.0
육류       31.0   26.0    31.0   26.0   31.0   26.0   31.0   26.0
일용잡화     43.0   21.0    43.0   21.0   43.0   21.0   43.0   21.0
젓갈/반찬    14.0   15.0    14.0   15.0   14.0   15.0   14.0   15.0
주류        3.0   11.0     3.0   11.0    3.0   11.0    3.0   11.0
주방가전      8.0   18.0     8.0   18.0    8.0   18.0    8.0   18.0
주방용품     18.0   14.0    18.0   14.0   18.0   14.0   18.0   14.0
차/커피     26.0   18.0    26.0   18.0   26.0   18.0   26.0   18.0
축산가공     19.0   16.0    19.0   16.0   19.0   16.0   19.0   16.0
침구/수예     4.0    NaN     4.0    NaN    4.0    NaN    4.0    NaN
캐주얼      60.0   41.0    60.0   41.0   60.0   41.0   60.0   41.0
커리어       6.0    3.0     6.0    3.0    6.0    3.0    6.0    3.0
통신/컴퓨터    1.0    2.0     1.0    2.0    1.0    2.0    1.0    2.0
트래디셔널    12.0   11.0    12.0   11.0   12.0   11.0   12.0   11.0
피혁잡화     21.0   19.0    21.0   19.0   21.0   19.0   21.0   19.0
화장품     196.0   68.0   196.0   68.0  196.0   68.0  196.0   68.0

In [42]:
X_train.groupby(['주구매상품','gender'])['주구매지점'].count().unstack()

gender      0      1
주구매상품
가공식품    317.0  229.0
가구        5.0    5.0
건강식품     22.0   25.0
골프       38.0   44.0
구두       26.0   28.0
기타      375.0  220.0
남성 캐주얼   13.0   42.0
남성 트랜디    1.0    1.0
남성정장      4.0   18.0
농산물     247.0   92.0
대형가전      4.0    4.0
디자이너    168.0   25.0
란제리/내의    6.0    2.0
명품       61.0   39.0
모피/피혁    39.0   18.0
보석        2.0    1.0
생활잡화      8.0    7.0
섬유잡화     48.0   50.0
셔츠       11.0   19.0
소형가전      1.0    1.0
수산품      92.0   61.0
스포츠      33.0   36.0
시티웨어    169.0   44.0
식기        2.0    5.0
아동       26.0   14.0
악기        NaN    2.0
액세서리      4.0    1.0
육류       31.0   26.0
일용잡화     43.0   21.0
젓갈/반찬    14.0   15.0
주류        3.0   11.0
주방가전      8.0   18.0
주방용품     18.0   14.0
차/커피     26.0   18.0
축산가공     19.0   16.0
침구/수예     4.0    NaN
캐주얼      60.0   41.0
커리어       6.0    3.0
통신/컴퓨터    1.0    2.0
트래디셔널    12.0   11.0
피혁잡화     21.0   19.0
화장품     196.0   68.0

In [14]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3500 entries, 0 to 3499
Data columns (total 11 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   cust_id  3500 non-null   int64
 1   총구매액     3500 non-null   int64
 2   최대구매액    3500 non-null   int64
 3   환불금액     3500 non-null   float64
 4   주구매상품    3500 non-null   object
 5   주구매지점    3500 non-null   object
 6   내점일수     3500 non-null   int64
 7   내점당구매건수  3500 non-null   float64
 8   주말방문비율   3500 non-null   float64
 9   구매주기     3500 non-null   int64
 10  gender   3500 non-null   int64
dtypes: float64(3), int64(6), object(2)
memory usage: 300.9+ KB

# 정제

In [49]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler, LabelEncoder, OneHotEncoder

In [43]:
X_train.head(5)

,cust_id,총구매액,최대구매액,환불금액,주구매상품,주구매지점,내점일수,내점당구매건수,주말방문비율,구매주기,gender
0,0,68282840,11264000,6860000.0,기타,강남점,19,3.894737,0.527027,17,0
1,1,2136000,2136000,300000.0,스포츠,잠실점,2,1.500000,0.000000,1,0
2,2,3197000,1639000,0.0,남성 캐주얼,관악점,2,2.000000,0.000000,1,1
3,3,16077620,4935000,0.0,기타,광주점,18,2.444444,0.318182,16,1
4,4,29050000,24000000,0.0,보석,본 점,2,1.500000,0.000000,85,0

In [91]:
X_train['총구매액'] = MinMaxScaler().fit_transform(X_train[['총구매액']])
X_train['최대구매액'] = MinMaxScaler().fit_transform(X_train[['최대구매액']])
X_train['환불금액'] = MinMaxScaler().fit_transform(X_train[['환불금액']])
X_train['내점일수'] = MinMaxScaler().fit_transform(X_train[['내점일수']])
X_train['내점당구매건수'] = MinMaxScaler().fit_transform(X_train[['내점당구매건수']])
X_train['구매주기'] = MinMaxScaler().fit_transform(X_train[['구매주기']])

In [123]:
ltmp = LabelEncoder().fit_transform(X_train['주구매상품'])
ltmp

array([ 5, 21,  6, ..., 32, 41,  5])

In [126]:
ltmp = ltmp.reshape(-1,1)
etmp = OneHotEncoder().fit_transform(ltmp)
etmp = etmp.toarray()
print(etmp)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 0.]]

In [92]:
X_train.head(5)

,cust_id,총구매액,최대구매액,환불금액,주구매상품,주구매지점,내점일수,내점당구매건수,주말방문비율,구매주기,gender
0,0,0.050810,0.020090,0.012168,기타,강남점,0.063380,0.137300,0.527027,0.102410,0
1,1,0.022966,0.007226,0.000532,스포츠,잠실점,0.003521,0.023715,0.000000,0.006024,0
2,2,0.023412,0.006526,0.000000,남성 캐주얼,관악점,0.003521,0.047431,0.000000,0.006024,1
3,3,0.028834,0.011171,0.000000,기타,광주점,0.059859,0.068511,0.318182,0.096386,1
4,4,0.034295,0.038037,0.000000,보석,본 점,0.003521,0.023715,0.000000,0.512048,0

In [103]:
import sklearn.preprocessing 
help(OneHotEncoder)

Help on class OneHotEncoder in module sklearn.preprocessing._encoders:

class OneHotEncoder(_BaseEncoder)
 |  Encode categorical features as a one-hot numeric array.
 |
 |  The input to this transformer should be an array-like of integers or
 |  strings, denoting the values taken on by categorical (discrete) features.
 |  The features are encoded using a one-hot (aka 'one-of-K' or 'dummy')
 |  encoding scheme. This creates a binary column for each category and
 |  returns a sparse matrix or dense array (depending on the ``sparse``
 |  parameter)
 |
 |  By default, the encoder derives the categories based on the unique values
 |  in each feature. Alternatively, you can also specify the `categories`
 |  manually.
 |
 |  This encoding is needed for feeding categorical data to many scikit-learn
 |  estimators, notably linear models and SVMs with the standard kernels.
 |
 |  Note: a one-hot encoding of y labels should use a LabelBinarizer
 |  instead.
 |
 |  Read more in the :ref:`User Guide <preprocessing_categorical_features>`.
 |
 |  .. versionchanged:: 0.20
 |
 |  Parameters
 |  ----------
 |  categories : 'auto' or a list of array-like, default='auto'
 |      Categories (unique values) per feature:
 |
 |      - 'auto' : Determine categories automatically from the training data.
 |      - list : ``categories[i]`` holds the categories expected in the ith
 |        column. The passed categories should not mix strings and numeric
 |        values within a single feature, and should be sorted in case of
 |        numeric values.
 |
 |      The used categories can be found in the ``categories_`` attribute.
 |
 |      .. versionadded:: 0.20
 |
 |  drop : {'first', 'if_binary'} or a array-like of shape (n_features,),             default=None
 |      Specifies a methodology to use to drop one of the categories per
 |      feature. This is useful in situations where perfectly collinear
 |      features cause problems, such as when feeding the resulting data
 |      into a neural network or an unregularized regression.
 |
 |      However, dropping one category breaks the symmetry of the original
 |      representation and can therefore induce a bias in downstream models,
 |      for instance for penalized linear classification or regression models.
 |
 |      - None : retain all features (the default).
 |      - 'first' : drop the first category in each feature. If only one
 |        category is present, the feature will be dropped entirely.
 |      - 'if_binary' : drop the first category in each feature with two
 |        categories. Features with 1 or more than 2 categories are
 |        left intact.
 |      - array : ``drop[i]`` is the category in feature ``X[:, i]`` that
 |        should be dropped.
 |
 |      .. versionchanged:: 0.23
 |         Added option 'if_binary'.
 |
 |  sparse : bool, default=True
 |      Will return sparse matrix if set True else will return an array.
 |
 |  dtype : number type, default=float
 |      Desired dtype of output.
 |
 |  handle_unknown : {'error', 'ignore'}, default='error'
 |      Whether to raise an error or ignore if an unknown categorical feature
 |      is present during transform (default is to raise). When this parameter
 |      is set to 'ignore' and an unknown category is encountered during
 |      transform, the resulting one-hot encoded columns for this feature
 |      will be all zeros. In the inverse transform, an unknown category
 |      will be denoted as None.
 |
 |  Attributes
 |  ----------
 |  categories_ : list of arrays
 |      The categories of each feature determined during fitting
 |      (in order of the features in X and corresponding with the output
 |      of ``transform``). This includes the category specified in ``drop``
 |      (if any).
 |
 |  drop_idx_ : array of shape (n_features,)
 |      - ``drop_idx_[i]`` is the index in ``categories_[i]`` of the category
 |        to be dropped for each feature.
 |      - ``drop_idx_[i] = None`` if no category is to be dropped from the
 |        feature with index ``i``, e.g. when `drop='if_binary'` and the
 |        feature isn't binary.
 |      - ``drop_idx_ = None`` if all the transformed features will be
 |        retained.
 |
 |      .. versionchanged:: 0.23
 |         Added the possibility to contain `None` values.
 |
 |  See Also
 |  --------
 |  OrdinalEncoder : Performs an ordinal (integer)
 |    encoding of the categorical features.
 |  sklearn.feature_extraction.DictVectorizer : Performs a one-hot encoding of
 |    dictionary items (also handles string-valued features).
 |  sklearn.feature_extraction.FeatureHasher : Performs an approximate one-hot
 |    encoding of dictionary items or strings.
 |  LabelBinarizer : Binarizes labels in a one-vs-all
 |    fashion.
 |  MultiLabelBinarizer : Transforms between iterable of
 |    iterables and a multilabel format, e.g. a (samples x classes) binary
 |    matrix indicating the presence of a class label.
 |
 |  Examples
 |  --------
 |  Given a dataset with two features, we let the encoder find the unique
 |  values per feature and transform the data to a binary one-hot encoding.
 |
 |  >>> from sklearn.preprocessing import OneHotEncoder
 |
 |  One can discard categories not seen during `fit`:
 |
 |  >>> enc = OneHotEncoder(handle_unknown='ignore')
 |  >>> X = [['Male', 1], ['Female', 3], ['Female', 2]]
 |  >>> enc.fit(X)
 |  OneHotEncoder(handle_unknown='ignore')
 |  >>> enc.categories_
 |  [array(['Female', 'Male'], dtype=object), array([1, 2, 3], dtype=object)]
 |  >>> enc.transform([['Female', 1], ['Male', 4]]).toarray()
 |  array([[1., 0., 1., 0., 0.],
 |         [0., 1., 0., 0., 0.]])
 |  >>> enc.inverse_transform([[0, 1, 1, 0, 0], [0, 0, 0, 1, 0]])
 |  array([['Male', 1],
 |         [None, 2]], dtype=object)
 |  >>> enc.get_feature_names(['gender', 'group'])
 |  array(['gender_Female', 'gender_Male', 'group_1', 'group_2', 'group_3'],
 |    dtype=object)
 |
 |  One can always drop the first column for each feature:
 |
 |  >>> drop_enc = OneHotEncoder(drop='first').fit(X)
 |  >>> drop_enc.categories_
 |  [array(['Female', 'Male'], dtype=object), array([1, 2, 3], dtype=object)]
 |  >>> drop_enc.transform([['Female', 1], ['Male', 2]]).toarray()
 |  array([[0., 0., 0.],
 |         [1., 1., 0.]])
 |
 |  Or drop a column for feature only having 2 categories:
 |
 |  >>> drop_binary_enc = OneHotEncoder(drop='if_binary').fit(X)
 |  >>> drop_binary_enc.transform([['Female', 1], ['Male', 2]]).toarray()
 |  array([[0., 1., 0., 0.],
 |         [1., 0., 1., 0.]])
 |
 |  Method resolution order:
 |      OneHotEncoder
 |      _BaseEncoder
 |      sklearn.base.TransformerMixin
 |      sklearn.base.BaseEstimator
 |      builtins.object
 |
 |  Methods defined here:
 |
 |  __init__(self, *, categories='auto', drop=None, sparse=True, dtype=<class 'numpy.float64'>, handle_unknown='error')
 |      Initialize self.  See help(type(self)) for accurate signature.
 |
 |  fit(self, X, y=None)
 |      Fit OneHotEncoder to X.
 |
 |      Parameters
 |      ----------
 |      X : array-like, shape [n_samples, n_features]
 |          The data to determine the categories of each feature.
 |
 |      y : None
 |          Ignored. This parameter exists only for compatibility with
 |          :class:`~sklearn.pipeline.Pipeline`.
 |
 |      Returns
 |      -------
 |      self
 |
 |  fit_transform(self, X, y=None)
 |      Fit OneHotEncoder to X, then transform X.
 |
 |      Equivalent to fit(X).transform(X) but more convenient.
 |
 |      Parameters
 |      ----------
 |      X : array-like, shape [n_samples, n_features]
 |          The data to encode.
 |
 |      y : None
 |          Ignored. This parameter exists only for compatibility with
 |          :class:`~sklearn.pipeline.Pipeline`.
 |
 |      Returns
 |      -------
 |      X_out : sparse matrix if sparse=True else a 2-d array
 |          Transformed input.
 |
 |  get_feature_names(self, input_features=None)
 |      Return feature names for output features.
 |
 |      Parameters
 |      ----------
 |      input_features : list of str of shape (n_features,)
 |          String names for input features if available. By default,
 |          "x0", "x1", ... "xn_features" is used.
 |
 |      Returns
 |      -------
 |      output_feature_names : ndarray of shape (n_output_features,)
 |          Array of feature names.
 |
 |  inverse_transform(self, X)
 |      Convert the data back to the original representation.
 |
 |      In case unknown categories are encountered (all zeros in the
 |      one-hot encoding), ``None`` is used to represent this category.
 |
 |      Parameters
 |      ----------
 |      X : array-like or sparse matrix, shape [n_samples, n_encoded_features]
 |          The transformed data.
 |
 |      Returns
 |      -------
 |      X_tr : array-like, shape [n_samples, n_features]
 |          Inverse transformed array.
 |
 |  transform(self, X)
 |      Transform X using one-hot encoding.
 |
 |      Parameters
 |      ----------
 |      X : array-like, shape [n_samples, n_features]
 |          The data to encode.
 |
 |      Returns
 |      -------
 |      X_out : sparse matrix if sparse=True else a 2-d array
 |          Transformed input.
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors inherited from sklearn.base.TransformerMixin:
 |
 |  __dict__
 |      dictionary for instance variables (if defined)
 |
 |  __weakref__
 |      list of weak references to the object (if defined)
 |
 |  ----------------------------------------------------------------------
 |  Methods inherited from sklearn.base.BaseEstimator:
 |
 |  __getstate__(self)
 |
 |  __repr__(self, N_CHAR_MAX=700)
 |      Return repr(self).
 |
 |  __setstate__(self, state)
 |
 |  get_params(self, deep=True)
 |      Get parameters for this estimator.
 |
 |      Parameters
 |      ----------
 |      deep : bool, default=True
 |          If True, will return the parameters for this estimator and
 |          contained subobjects that are estimators.
 |
 |      Returns
 |      -------
 |      params : dict
 |          Parameter names mapped to their values.
 |
 |  set_params(self, **params)
 |      Set the parameters of this estimator.
 |
 |      The method works on simple estimators as well as on nested objects
 |      (such as :class:`~sklearn.pipeline.Pipeline`). The latter have
 |      parameters of the form ``<component>__<parameter>`` so that it's
 |      possible to update each component of a nested object.
 |
 |      Parameters
 |      ----------
 |      **params : dict
 |          Estimator parameters.
 |
 |      Returns
 |      -------
 |      self : estimator instance
 |          Estimator instance.